[snowflake]
user = "ajaya"
password = "Ajay@@@123"
account = "qzb39751-ncb_jamaica"
warehouse="DEV_ENGG_ELT_WH"
database="JNCB_DATAREADY_DEV_ALL"
schema="MSEG_TRANSFORMED_DATA"
role="ACCOUNTADMIN"
client_session_keep_alive = true